### ISSUE TITLE
Web UI Tracking

### ISSUE THREAD

**Issue by DougLau** [mnit-rtmc/iris#101]
This issue tracks tasks needed for the Web UI.

- [x] Change earthwyrm to use rosewood/loam instead of PostGIS
- [x] Update to modern version of Leaflet JS library
- [x] Handle Leaflet events by updating selected items, etc.
- [x] Add tooltips for devices
- [x] Merge into a single service, using axum
- [x] Generate freeway segment layer (loam) for earthwyrm
- [x] Implement SSE messages for selected card / resource type
- [x] Verify user's network domain on login
- [x] #162 
- [x] #164 
- [x] #83
