### ISSUE TITLE
Web UI DMS checklist

### ISSUE THREAD

**Issue by DougLau** [mnit-rtmc/iris#162]
- [x] Generate map layer loam file on configuration changes
- [x] Use substitute message patterns (for extra-wide signs)
- [x] Allow free-form text entry for users with permissions
- [x] Add UI for message duration / expiration
- [x] Selecting a card should select map marker, and center map
- [x] Default to deployed item state (not all)
- [x] Add sign location to compact card
- [ ] Pixel errors UI
- [ ] Setup card: add beacon, preset
- [x] Request card w/ TAMS work request link, query msg, config, status, settings, send settings, reset
- [x] Status card w/ brightness, power, temp
- [x] Sign config / details cards
- [ ] Add emojis based on linked incident type (💥🚗, 🔧⛽, 🕳️🪨, 🚧🦺)
