### ISSUE TITLE
Web UI camera checklist

### ISSUE THREAD

**Issue by DougLau** [mnit-rtmc/iris#163]
- [x] Add to map
 - [ ] Allow unpublish / publish
 - [ ] View properties, like IP addresses
 - [ ] Reboot button
 - [ ] Recall / set presets
