### ISSUE TITLE
Web UI ramp meter checklist

### ISSUE THREAD

**Issue by DougLau** [mnit-rtmc/iris#83]
- [x] Map markers
- [x] Initial lock rate should match ramp demand
- [x] Associate user name with lock
- [x] Lock duration, defaulting to 15 minutes
- [x] Lock reasons: knocked down, indication
- [x] Add UI to set/clear locks
